### PR TITLE
Refurbishment

### PR DESCRIPTION
**Pull request by woctezuma**
The fix to the following issue is present in this pull request, but I will submit it as well in another much shorter pull request:
- #24

### CODE REVIEW

**Comment by woctezuma** [comment]
I see there are places with double quotes and places with single quotes in the original code.
Ideally, I would not have edited these, since there is some inconsistency in the usage.

**Comment by SD4RK** [comment]
Hello,

Thanks for the contribution, but something seems wrong with the changed naming of "EGSExceptionError", it should be either just Exception or just Error, and I think to remain consistent with Python it should remain Exception, EGSNotFound could be changed to EGSNotFoundException too, I guess. 
Regarding double/single quotes - I honestly don't remember what the reasoning was when I were writing this code, if there ever was a reasoning at all lol.

**Comment by woctezuma** [comment]
Alright. I have preserved quotes, and skipped renaming exceptions.

**Comment by SD4RK** [comment]
Thank you, merged.

**Pull request merged**
